spring.application.name=gestionEtudiants
server.port=8081
mysql.host=jdbc:mysql://localhost:3306/gestionEtudiants
mysql.username=root
mysql.password=abiba@1997
mysql.driver=com.mysql.cj.jdbc.Driver

spring.autoconfigure.exclude = org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#spring.mvc.cors.allowed-origins=http://localhost:4200
#spring.mvc.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
#spring.mvc.cors.allowed-headers=*
#spring.mvc.cors.allow-credentials=true
#spring.mvc.cors.exposed-headers=*
